<#import "/spring.ftl" as spring/>

<html lang="">
<head>
    <title>Main</title>
    <style>
        body {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%)
        }
    </style>
</head>
<body>
<div align="center">
    <h3>You have signed up successfully!</h3>
    <p>Please check your email to verify your account.</p>
    <h4><a href="/signIn">Click here to Login</a></h4>
</div>
</body>
</html>