<html lang="">
<head>
    <title>Admin Panel</title>
    <style>
        body {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%)
        }
    </style>
</head>
<body>
<div align="center">
    <h2>Admin Panel</h2>
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='/';" value="Menu" />
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='panel/halls';" value="Halls" />
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='panel/films';" value="Films" />
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='panel/sessions';" value="Sessions" />
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='/logout';" value="Log out" />
    <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
</div>
</body>
</html>