<html lang="">
<head>
    <title>Main</title>
    <style>
        body {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%)
        }
    </style>
</head>
<body>
<div align="center">
    <h2>Main</h2>
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='session/search';" value="Cinema" />
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='profile';" value="Profile" />
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='signIn';" value="Log in" />
    <input type="button" style="width: 150px; height: 50px;" onclick="location.href='signUp';" value="Sign up" />
</div>
</body>
</html>